name: example
description: A simple command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  agent_dart: ^0.1.24+1
  collection: ^1.17.0

dev_dependencies:
  build_runner: ^2.3.3
  candid_dart:
    path: ../
  lints: ^2.0.1
