name: candid_example
publish_to: 'none'

environment:
  sdk: ^3.4.0

dependencies:
  agent_dart_base:
  collection:
  freezed_annotation:
  meta:

dev_dependencies:
  build_runner:
  candid_dart:
    path: ../packages/candid
