targets:
  $default:
    builders:
      candid_dart_build|candid2dart:
        generate_for:
          - lib/**/**.did
        options:
          freezed: false
          copy_with: true
          equal: true
          service: true
          make_collections_unmodifiable: true
          explicit_serialization_methods: true
