name: demo_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  agent_dart: ^1.0.0-dev.11
  auto_size_text: ^3.0.0
  collection: ^1.17.0
  decimal: ^2.3.2
  extended_sliver: ^2.1.3
  fl_chart: ^0.62.0
  flex_color_picker: ^3.2.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  mobile_scanner: ^3.2.0
  modal_bottom_sheet: ^3.0.0-pre
  oktoast: ^3.3.1
  recase: ^4.1.0
  sliver_tools: ^0.2.10
  waterfall_flow: ^3.0.2

dev_dependencies:
  candid_dart_build: ^1.1.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: ^2.0.1
  freezed: ^2.3.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
