# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  candid2DartBuilder:
    import: "package:candid_dart/builder.dart"
    builder_factories: [ "candid2DartBuilder" ]
    build_extensions: { ".did": [ ".idl.dart" ] }
    build_to: source
    auto_apply: root_package