name: candid_dart

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: true
    runPubGetOffline: false

  version:
    branch: main
    linkToCommits: false
    includeCommitId: true
    includeScopes: true
    workspaceChangelog: true
    updateGitTagRefs: true
    releaseUrl: false

scripts:
  upgrade: melos exec -- dart pub upgrade --null-safety
  pub-get: melos exec -- dart pub get
  prepare: melos bootstrap
  analyze:
    exec: dart analyze .
  publish: melos publish --no-dry-run --ignore="*example*" --yes
  dry-run: melos publish --dry-run --ignore="*example*"

ide:
  intellij:
    enabled: true
    moduleNamePrefix: ''
