name: candid_dart
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  antlr4: ^4.10.1
  build_runner: ^2.1.10
  dart_style: ^2.2.3
  mustache_template: ^2.0.0
  recase: ^4.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
