name: candid_dart
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  antlr4: ^4.12.0
  build: ^2.3.0
  build_runner: ^2.3.3
  dart_style: ^2.2.5
  mustache_template: ^2.0.0
  recase: ^4.1.0
  tuple: ^2.0.1

dev_dependencies:
  lints: any
  test: any
