name: candid_dart_example
description: A simple command-line application.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  agent_dart: ^1.0.0-dev.11
  collection: ^1.17.0
  freezed_annotation: ^2.2.0
  recase: ^4.1.0

dev_dependencies:
  lints: any
  build_runner: ^2.3.3
  candid_dart: ^1.1.5
  freezed: ^2.3.2
