name: candid_dart_core
description: Provide the `did2dart` method to process `Candid` content, and quickly generate corresponding Dart code.
version: 1.1.6
homepage: https://github.com/AstroxNetwork
repository: https://github.com/AstroxNetwork/candid_dart
issue_tracker: https://github.com/AstroxNetwork/candid_dart/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  antlr4: ^4.13.1
  build_runner: ^2.3.3
  built_collection: ^5.1.1
  built_value: ^8.4.4
  code_builder: ^4.4.0
  collection: ^1.17.0
  dart_style: ^2.3.1
  pub_semver: ^2.1.4
  recase: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
